"""set email length to 100

Revision ID: aededc8b2349
Revises: 7db44b27f4c9
Create Date: 2025-04-17 22:05:40.949299

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aededc8b2349"
down_revision: Union[str, None] = "7db44b27f4c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(length=90), type_=sa.String(length=100), existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "email", existing_type=sa.String(length=100), type_=sa.VARCHAR(length=90), existing_nullable=False
    )
    # ### end Alembic commands ###
